### PR TITLE
Add new alloc call hints to LLVM

### PR DESCRIPTION
**Pull request by jacob-hughes**
We need to patch LLVM in rustgc so this repo is intended to replace the `rust-lang/llvm-project` submodule. Notice though that the branching system is a little different to what we're used to. Rust never checks out LLVM's master branch. Instead, rust specific release branches are created where interesting commits are cherry-picked across from master. These branches also contain rust specific patches (which are never merged back into master). These look a bit like this:

`llvm-project:rustc/11.0-2020-10-12`

I've structured this fork to work in the same way. So the base branch for this PR is:

`rustgc-llvm-fork:rustgc/11.0-2020-10-12`

This base branch tracks the corresponding branch in Rust's LLVM fork, and occasionally when a new in-tree release of LLVM is rolled by rustc, we will need to update this too as part of the upstream sync of rustgc.

The commit ada81b0 describes this particular patch.

### CODE REVIEW

**Comment by ltratt** [comment]
Before we spread the term "atomic" over multiple repos, I wonder if we should think of an alternative now? I can be persuaded otherwise!

**Comment by jacob-hughes** [comment]
95510e7 renames alloc_atomic -> alloc_untraceable. What do you think?

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
